"""add_actor_currency_portfolio_rebalance_tables

Revision ID: c0ebfb0eb6cc
Revises: 0c92c803d35b
Create Date: 2026-02-27 16:01:02.816653

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0ebfb0eb6cc"
down_revision: Union[str, None] = "0c92c803d35b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "xarizmi_actor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset", sa.Float(), nullable=False),
        sa.Column("actor_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "xarizmi_currency",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "xarizmi_portfolio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("datetime"),
    )
    op.create_table(
        "xarizmi_portfolio_allocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "xarizmi_rebalance_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "xarizmi_portfolio_allocation_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("allocation_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["xarizmi_portfolio_allocation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["xarizmi_symbol.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "xarizmi_rebalance_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("result_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("current_weight", sa.Float(), nullable=False),
        sa.Column("target_weight", sa.Float(), nullable=False),
        sa.Column("current_market_value", sa.Float(), nullable=False),
        sa.Column("target_market_value", sa.Float(), nullable=False),
        sa.Column("delta_market_value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["xarizmi_rebalance_result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["xarizmi_symbol.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "xarizmi_portfolio_item",
        sa.Column("portfolio_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "xarizmi_portfolio_item",
        "xarizmi_portfolio",
        ["portfolio_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "xarizmi_portfolio_item", type_="foreignkey")
    op.drop_column("xarizmi_portfolio_item", "portfolio_id")
    op.drop_table("xarizmi_rebalance_item")
    op.drop_table("xarizmi_portfolio_allocation_item")
    op.drop_table("xarizmi_rebalance_result")
    op.drop_table("xarizmi_portfolio_allocation")
    op.drop_table("xarizmi_portfolio")
    op.drop_table("xarizmi_currency")
    op.drop_table("xarizmi_actor")
    # ### end Alembic commands ###
